### ISSUE TITLE
Available as a bower install

### ISSUE THREAD

**Issue by devakone** [mattslocum/ng-webworker#1]
Are you planning to make this available as a bower package?

**Comment by mattslocum** [comment]
That's a great idea. If you or someone wants to help do that it would be awesome. Otherwise, I'll try and get to it, but I'm not sure I have time this weekend.

**Comment by mattslocum** [comment]
Actually it looks pretty simple. I'll try and put it on bower this weekend

**Comment by devakone** [comment]
good deal, it's really not that bad!

**Comment by mattslocum** [comment]
I'm actually working on additional features and a slight refactor that supports transferable objects and a different config structure. It will have small breaking changes for advanced users. Hopefully I'll get that done very soon.

**Comment by devakone** [comment]
Sounds good! Good project and work overall!

**Comment by mattslocum** [comment]
http://bower.io/search/?q=ng-webworker

Don't forget to star my project on github since that is what bower uses for ranking.

**Comment by devakone** [comment]
By the way, i was testing with a worker that returned an array and it was not working, is this related to the transferable fix you just put it?

**Comment by mattslocum** [comment]
Maybe. Can you show me a sample of your code?

**Comment by mattslocum** [comment]
It works on jsfiddle: 
http://jsfiddle.net/mslocum/9fmh6uyo/

**Comment by devakone** [comment]
It must have been on my side! No worries! One other aspect i am thinking about is clean up. How do you clean up if for example the controller is destroyed while the worker has not posted back the answer yet?

**Comment by mattslocum** [comment]
Like most developers, I suck at documentation.

myWorker.terminate() to just kill it.
myWorker.stop() to reject the promise and terminate. stop() calls terminate() internally so you don't need to call them both.

**Comment by devakone** [comment]
Excellent! That's why the community is here :-)

**Comment by mattslocum** [comment]
I also noticed while using 0.1 that it looked like chrome created a new webworker thread ever time run() was called. This appeared to be a memory/thread leak, so I [added terminate](https://github.com/mattslocum/ng-webworker/blob/master/src/ng-webworker.js#L233) to each promise finally(). 

This seemed to fix the leak problem, but it changes the workflow slightly. Now you have to do webworker.create() every time before you run(). It might be worth a little more investigation or maybe a config flag.

**Comment by devakone** [comment]
I noticed that too but it thought it was on design. Creating a new webworker everytime is more in line with the way it works outside angular so I see no issues there.
