### ISSUE TITLE
Uploading multiple files using the WebWorker

### ISSUE THREAD

**Issue by canvasmanager** [mattslocum/ng-webworker#10]
Hi Matt,

Thankyou for creating this control. Works well.

I am trying to upload some files using this control in the Web Worker. I have kept the following code:

var uploadOriginalFiles=function(host,files) {
    for(var i=0;i<files.length;i++){
        var file = files[i];  
        var formData = new FormData();
        formData.append("image", file);
        var filename = filenames[i];
        var request = new XMLHttpRequest();
        request.timeout = 0;
        request.cache=false;
        request.onreadystatechange = function() {  
            if (request.readyState == 4) {
                if(request.status == 200) {
                    console.log(filename + " uploaded");
                }else{
                                       console.log("Upload failed");
                                }
            }
        };
        request.open("POST", host);  
        request.send(formData);
    }
};

var myWorker = Webworker.create(uploadOriginalFiles,{async: true});
            myWorker.run(host,files).then(function(result) {
                alert("Finished: " + result);
            }).catch(function(err){
                alert("Sorry, could not process your photo. The quality might be compromised. Please try again");
           });

This code is working fine apart from the case if I am trying to upload multiple files (~6 files) with ~2MB each, I completes for some of the files, but fails for other of them. Checked the status for the request.readyState at 0,1,2,3,4. For some of the files, sometimes it does not even move to readyState 1, while if I try to upload the same file (single file only), it works fine. Is there some issue with memory with the web worker? Can you help me please?

**Comment by ivanovjaroslaw** [comment]
@canvasmanager 
I tried to upload 7 csv files with 3mb size. All of them uploaded successfully (readyState also getting 0,1,2,3,4 values). I am using Chrome. 

http://codepen.io/anon/pen/WrGMqN?editors=101

But I got something strange in console: "Some file finished" appears 4431 times. It seems that onreadystatechange is problem.

Can you write what happened with your other requests? Stay freezzing and pending? It needs more debug information.

**Comment by mattslocum** [comment]
Did you get it working? My wife was having a new baby about the time of your original post, so I wasn't paying any attention to github. I'll close this unless you are still having a problem.

**Comment by canvasmanager** [comment]
Yes, I was able to get it to working. The change, which I did in my worker process code was:

I keep on calling the upload again and again till the request status is not returned as 200.
Thanks,
Manik Mittal
