### ISSUE TITLE
digest error

### ISSUE THREAD

**Issue by mistic** [mattslocum/ng-webworker#14]
Hi :),

I'm trying to use this module but i'm facing some troubles. 

I'm trying to call a worker with controller $scope as param (i need some functions and other things of controller's $scope) but i'm getting this error:

[$rootScope:inprog] $digest already in progress

Any idea?

Regards

**Comment by mattslocum** [comment]
[From MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Transferring_data_to_and_from_workers_further_details): Objects are serialized as they're handed to the worker, and subsequently, de-serialized on the other end. The page and worker do not share the same instance, so the end result is that a duplicate is created on each end. Most browsers implement this feature as structured cloning.

I'm not sure why you'd see $digest already in progress. I'm guessing that doesn't have anything to do with this library. The library doesn't call $digest. In fact, it doesn't even use $scope.
