### ISSUE TITLE
Notify and Complete not defined

### ISSUE THREAD

**Issue by synapse** [mattslocum/ng-webworker#15]
I'm getting this message when I'm trying to use use complete and notify function inside the web worker.
The worker is working, the problem is with these to function.

`Uncaught ReferenceError: complete is not defined` 
and
`Uncaught ReferenceError: notify is not defined`

**Comment by synapse** [comment]
I think I found the problem.
When I minimize my app the worker and both the notify and complete functions are minified so the original two function are not found any more. This is my code after the minification

``` javascript
function s(e) {
    postMessage(["complete", e], _transferable_(e))
}

function u(e) {
    postMessage(["notice", e])
}

function a(db) {
    console.log("This is your worker speaking", db), setTimeout(function() {
        notify("Hello")
    }, 2e3)
};
onmessage = function(e) {;
    var result = a.apply(null, e.data);
    postMessage(['return', result], !_async_ ? _transferable_(result) : [])
};
var _async_ = true;

function i(e) {
    var t = [];
    return "[object Array]" != toString.apply(e) && (e = [e]), e.forEach(function(e) {
        e instanceof ArrayBuffer && t.push(e)
    }), t
}
```

**Comment by mattslocum** [comment]
If you are minifying ng-webworker yourself, then you will need to tell you minifier not to change those functions. See how I did it for uglify: https://github.com/mattslocum/ng-webworker/blob/master/Gruntfile.js#L38
