### ISSUE TITLE
What about using ngResource, etc. Inside the web worker?

### ISSUE THREAD

**Issue by surfjedi** [mattslocum/ng-webworker#2]
I tried a to execute some ngResource calls in the web worker but $resource, and other things weren't avalable inside the worker.

Any thoughts on this?

**Comment by mattslocum** [comment]
It can get a little confusing. You can write a function in your angular app, but it converts it into its own thread. Lexical scope of variables that you are used to cannot be shared between your worker function at your main code. You have to basically think of your function like it is in a different file.

It is however possible to load other files like angular into your webworker, but I'm not sure what features will and wont work. It might require some core modifications to even run. If you try this, keep in mind that there is no DOM to bootstrap in the worker. Also, require.js is also webworker compatible if you like require.
