### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by amilajack** [mattslocum/ng-webworker#26]
I thought the DOM wasn't thread safe and that accessing the DOM from web workers was impossible. How did you achieve this?

**Comment by mattslocum** [comment]
Browsers have the ability to process data in separate threads and message back and forth. The DOM can only be edited from the main browser. You can read more about web-workers on MDN: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

This library dynamically converts functions into web workers. When it does this the web worker is 100% in isolation from the code that you created it from, so don't try to access any other variables or functions that you didn't include or pass into your web worker.

You can check out my examples: http://mattslocum.github.io/ng-webworker/demo/
