### ISSUE TITLE
Shortcut for including external libraries / functions

### ISSUE THREAD

**Issue by amergin** [mattslocum/ng-webworker#3]
Would be nice if `ng-webworker` provided a shortcut for including external libraries (by using [`importScripts`](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts)). I can think of several libraries that could be used in a computation thread, such as `numeric.js` and `lodash.js`. Some WW abstraction libraries even allow to pass arbitrary functions.

**Comment by mattslocum** [comment]
Sure, you can use importScripts. Your code runs inside a web worker. So you can add any native web worker functions. I just added a demo for you at the bottom of my demo site.

http://mattslocum.github.io/ng-webworker/demo/
