### ISSUE TITLE
Module not found: Error: Cannot resolve module 'ng-webworker'

### ISSUE THREAD

**Issue by edgaraskazlauskas** [mattslocum/ng-webworker#34]
Occurs when doing `require("ng-webworker");`. A more detailed error:

> Module not found: Error: Cannot resolve module 'ng-webworker' in /Users/Nddt/web-app/app/components
resolve module ng-webworker in /Users/Nddt/web-app/app/components
looking for modules in /Users/Nddt/web-app/node_modules
resolve 'file' ng-webworker in /Users/Nddt/web-app/node_modules
resolve file
/Users/Nddt/web-app/node_modules/ng-webworker is not a file
/Users/Nddt/web-app/node_modules/ng-webworker.webpack.js doesn't exist
/Users/Nddt/web-app/node_modules/ng-webworker.web.js doesn't exist
/Users/Nddt/web-app/node_modules/ng-webworker.js doesn't exist
/Users/Nddt/web-app/node_modules/ng-webworker.json doesn't exist
resolve 'file' or 'directory' /Users/Nddt/web-app/node_modules/ng-webworker
resolve file
/Users/Nddt/web-app/node_modules/ng-webworker is not a file
/Users/Nddt/web-app/node_modules/ng-webworker.webpack.js doesn't exist
/Users/Nddt/web-app/node_modules/ng-webworker.web.js doesn't exist
/Users/Nddt/web-app/node_modules/ng-webworker.js doesn't exist
/Users/Nddt/web-app/node_modules/ng-webworker.json doesn't exist
resolve directory
directory default file index
resolve file index in /Users/Nddt/web-app/node_modules/ng-webworker
/Users/Nddt/web-app/node_modules/ng-webworker/index doesn't exist
/Users/Nddt/web-app/node_modules/ng-webworker/index.webpack.js doesn't exist
/Users/Nddt/web-app/node_modules/ng-webworker/index.web.js doesn't exist
/Users/Nddt/web-app/node_modules/ng-webworker/index.js doesn't exist
/Users/Nddt/web-app/node_modules/ng-webworker/index.json doesn't exist
[/Users/Nddt/web-app/node_modules/ng-webworker.webpack.js]
[/Users/Nddt/web-app/node_modules/ng-webworker.webpack.js]
[/Users/Nddt/web-app/node_modules/ng-webworker.web.js]
[/Users/Nddt/web-app/node_modules/ng-webworker.web.js]
[/Users/Nddt/web-app/node_modules/ng-webworker.js]
[/Users/Nddt/web-app/node_modules/ng-webworker.js]
[/Users/Nddt/web-app/node_modules/ng-webworker.json]
[/Users/Nddt/web-app/node_modules/ng-webworker.json]
[/Users/Nddt/web-app/node_modules/ng-webworker/index]
[/Users/Nddt/web-app/node_modules/ng-webworker/index.webpack.js]
[/Users/Nddt/web-app/node_modules/ng-webworker/index.web.js]
[/Users/Nddt/web-app/node_modules/ng-webworker/index.js]
[/Users/Nddt/web-app/node_modules/ng-webworker/index.json]
@ ./app/components/app.js 23:4-27

**Comment by KanoczTomas** [comment]
I have the same issue :(

**Comment by RobARichardson** [comment]
Same here. Trying to use Webpack 2 and ES6 imports.

**Comment by mattslocum** [comment]
O, I bet that is because there isn't an index.js file at the root of the project. I bet if you do 
`require('ng-webworker/src/ng-webworker')` then webpack would be happy. Either that or use the NormalModuleReplacementPlugin to make it so `ng-webworker` resolves to the longer path.

 I'm working on fixing this as well as some other overhauls. I just finished re-writing it in typescript. Now I think I can port it to angular as well as angularjs. Maybe at the same time... we'll see.

**Comment by RobARichardson** [comment]
@mattslocum I ended up using Webpack's resolve feature (https://webpack.js.org/configuration/resolve/) to get it working; nearly the same solution you suggested.

Looking forward to the rewrite.  I'm also using TypeScript and it would be nice to have typing support for ng-webworker.
