### ISSUE TITLE
Better examples in documentation

### ISSUE THREAD

**Issue by mavrick** [mattslocum/ng-webworker#39]
Hey there,

Nice wrapper on the service worker - has been very handy to solve a few blocking issues for me in angular. I had to do a bit of digging around in source code to get the solution I was after for creating a separate file to run the worker from. 

I see that in the examples on the website that it was possible but didn't see anything else past that. I'd be happy to create some but I've only used the library for less than 48 hours so I may not have the best use-cases to provide examples that could be beneficial to the wider community. 

What I could suggest is a few use-cases and we could build off them with feedback to come up with some better code examples?

Cheers,

Dan

**Comment by mattslocum** [comment]
yeah. what use cases do you suggest?
